<?php

/**
 * PluginImportDiaryJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImportDiaryJobTable extends ImportJobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImportDiaryJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImportDiaryJob');
    }
}