<?php

/**
 * PluginOp2DiaryImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2DiaryImage extends BaseOp2DiaryImage
{

}
