<?php

/**
 * PluginOp2Member
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Member extends BaseOp2Member
{
  public function getDiaries()
  {
    return Doctrine::getTable('Op2Diary')->getDiaries($this->id);
  }

  public function setName($name)
  {
    $member = $this->getTable()->findOneByName($name);
    if ($member)
    {
      $this->assignIdentifier($member->identifier());
    }
    else
    {
      $this->_set('name', $name);
    }
  }
}
