<?php

/**
 * PluginOp2CommunityEventMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2CommunityEventMember extends BaseOp2CommunityEventMember
{

}