<?php

/**
 * PluginImportTopicJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImportTopicJobTable extends ImportJobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImportTopicJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImportTopicJob');
    }
}