<?php

/**
 * PluginOp2Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Image extends BaseOp2Image
{
  public function fetchImage($imageUrl = null)
  {
    if (!is_null($imageUrl))
    {
      $this->orig_url = $imageUrl;
    }

    $tmppath = tempnam(sys_get_temp_dir(), 'IMG');
    $fh = fopen($tmppath, 'w');

    $c = curl_init();
    curl_setopt_array($c, array(
      CURLOPT_URL => $imageUrl,
      CURLOPT_HEADER => false,
      CURLOPT_FILE => $fh,
    ));
    curl_exec($c);
    curl_close($c);

    fclose($fh);

    $validator = new opValidatorImageFile();
    $validFile = $validator->clean(array('tmp_name' => $tmppath));

    $this->File = new File();
    $this->File->setFromValidatedFile($validFile);
  }
}
