<?php

/**
 * PluginOp2Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Comment extends BaseOp2Comment
{
  public function setFromArray($comment)
  {
    if ($comment['AUTHOR'])
    {
      $member = new Op2Member();
      $member->name = $comment['AUTHOR'];
      $this->Op2Member = $member;
    }
    $this->created_at = date('Y-m-d H:i:s', strtotime($comment['DATE']));
    $this->body = $comment['content'];
  }
}
