<?php

/**
 * PluginOp2Entry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Entry extends BaseOp2Entry
{
  public function setFromArray(array $entry)
  {
    $this->title = $entry['TITLE'];
    $this->created_at = date('Y-m-d H:i:s', strtotime($entry['DATE']));

    $this->setBodyArray($this->splitBody($entry['BODY']));

    $member = new Op2Member();
    $member->name = $entry['AUTHOR'];
    $this->Op2Member = $member;
  }

  protected function setBodyArray(array $body)
  {
    $this->body = $this->br2nl($body['body']);

    if (isset($body['images']))
    {
      $this->has_images = true;

      foreach ($body['images'] as $num => $imageUrl)
      {
        $this->addImage($imageUrl, $num);
      }
    }
  }

  protected function br2nl($html)
  {
    $html = preg_replace("/[\r\n]+/", '', $html);
    $html = preg_replace('/<br.*?>/', "\n", $html);
    return $html;
  }

  protected function addImage($imageUrl, $idx)
  {
  }

  public function getCommentsCount()
  {
    return -1;
  }

  public function getCommentTable()
  {
    $tableName = get_class($this).'Comment';
    return Doctrine::getTable($tableName);
  }

  protected function splitBody($body)
  {
    if (0 !== strpos($body, '<p>'))
    {
      return array('body' => $body);
    }

    $result = array();

    $body = split('</p>', $body, 2);
    $result['body'] = $body[1];

    $meta = split("\n", str_replace('<p>', '', $body[0]));
    foreach ($meta as $line)
    {
      $line = ltrim($line);
      if (false !== strpos($line, '<img'))
      {
        $result['images'][] = preg_replace('/^\s*<img src="(.*?)">$/', '$1', $line);
      }
      else
      {
        $line = split(' : ', $line, 2);
        $result[$line[0]] = $line[1];
      }
    }

    return $result;
  }
}
