<?php

/**
 * PluginOp2DiaryCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2DiaryCategory extends BaseOp2DiaryCategory
{
  public function setName($name)
  {
    $cat = $this->getTable()->findOneByName($name);
    if ($cat)
    {
      $this->assignIdentifier($cat->identifier());
    }
    else
    {
      $this->_set('name', $name);
    }
  }
}
