<?php

/**
 * PluginOp2Diary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Diary extends BaseOp2Diary
{
  protected function addImage($imageUrl, $idx)
  {
    $image = new Op2DiaryImage();
    $image->fetchImage($imegeUrl);
    $image->number = $idx;

    $this->Op2DiaryImage[] = $image;
  }

  public function getCommentsCount()
  {
    return Doctrine::getTable('Op2DiaryComment')->createQuery()
      ->where('op2_diary_id = ?', $this->id)
      ->count();
  }
}
