<?php

/**
 * PluginOp2DiaryCategoryDiary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2DiaryCategoryDiary extends BaseOp2DiaryCategoryDiary
{

}