<?php

/**
 * PluginOp2Community
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2Community extends BaseOp2Community
{
  public function setName($name)
  {
    $community = $this->getTable()->findOneByName($name);
    if ($community)
    {
      $this->assignIdentifier($community->identifier());
    }
    else
    {
      $this->_set('name', $name);
    }
  }

  public function getTopics()
  {
    return Doctrine::getTable('Op2CommunityTopic')->getTopics($this->id);
  }

  public function getEvents()
  {
    return Doctrine::getTable('Op2CommunityEvent')->getEvents($this->id);
  }
}
