<?php

/**
 * PluginOp2DiaryComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2DiaryComment extends BaseOp2DiaryComment
{

}
