<?php

/**
 * PluginOp2CommunityTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2CommunityTopic extends BaseOp2CommunityTopic
{
  public function getCommentsCount()
  {
    return Doctrine::getTable('Op2CommunityTopicComment')->createQuery()
      ->where('op2_community_topic_id = ?', $this->id)
      ->count();
  }
}
