<?php

/**
 * PluginOp2CommunityEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2CommunityEvent extends BaseOp2CommunityEvent
{
  public function setBodyArray(array $body)
  {
    parent::setBodyArray($body);

    $openDate = explode(' ', $body['開催日時'], 2);
    $this->open_date = $openDate[0];
    $this->open_date_comment = $openDate[1];
    $this->area = $body['開催場所'];
    $this->Op2Community = new Op2Community();
    $this->Op2Community->name = $body['関連コミュニティ'];
  }

  public function getCommentsCount()
  {
    return Doctrine::getTable('Op2CommunityEventComment')->createQuery()
      ->where('op2_community_event_id = ?', $this->id)
      ->count();
  }
}
