<?php

/**
 * PluginOp2CommunityTopicComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMTViewerPlugin
 * @subpackage model
 * @author     Kimura Youichi <kim.upsilon@gmail.com>
 */
abstract class PluginOp2CommunityTopicComment extends BaseOp2CommunityTopicComment
{

}