homeSuccess:
  customize:
    mtviewerTopicList:
      template: [mtviewer_topic, topicList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true

    mtviewerEventList:
      template: [mtviewer_event, eventList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true
